SET SERVEROUTPUT ON

CREATE OR REPLACE PROCEDURE SALUDO(NOMBRE VARCHAR)
IS
    SALU VARCHAR(20):='HOLA, ';
BEGIN

    SALU := SALU || NOMBRE;
    
    dbms_output.put_line(SALU);
    
END;

EXECUTE SALUDO('ALFREDO');


CREATE OR REPLACE FUNCTION SUMA(NUM1 NUMBER, NUM2 NUMBER)
RETURN NUMBER AS
BEGIN
    
    RETURN NUM1+NUM2;

END;

SELECT SUMA(3,5) AS SUMA FROM DUAL;
