SET SERVEROUTPUT ON;

CREATE SEQUENCE SQ_PER START WITH 1 INCREMENT BY 1 MAXVALUE 100 MINVALUE 1

BEGIN
    DBMS_OUTPUT.PUT_LINE(SQ_PER.NEXTVAL);
END;


CREATE VIEW ObraView as(SELECT * FROM OBRA);

SELECT * From ObraView;
